name: Lint and Build

on:
  push:
    branches:
      - '**' # Trigger on every commit to any branch

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    name: Lint and Build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Lint add-on
        run: web-ext lint --source-dir ./

      - name: Build add-on
        run: |
          web-ext build \
            --source-dir ./ \
            --artifacts-dir ./web-ext-artifacts
